[build]
  publish = "."
  command = ""

[[headers]]
  for = "/app/*.jsx"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/app/*.js"
  [headers.values]
    Cache-Control = "no-cache"
